= AI concepts




== Large language models (LLMs)

Large language models (LLMs) are machine learning models trained to generate a sequence of outputs based on a sequence of inputs (often text inputs and outputs, but some LLMs can work with images, audio or video). LLMs (also known as foundation or frontier models) can perform a wide variety of tasks, such as summarizing a document, translating between languages, fact extraction, writing code, etc. 


== Prompts and prompting

Calling an LLM, whether from an application or as an end-user in a chat interface, involves writing a prompt. A prompt is the information (usually text) that the LLM uses to generate its response. If you think of communicating with an LLM like communicating with another person, how you phrase your request is important to making sure the other person (or the LLM, in this case) understands what you want to know.

At its simplest, a prompt is built from the system message and the user message, but often also includes chat memory. System messages give the LLM contextual information and instructions for handling the request, often including examples that you want the LLM to follow when generating its response. User messages provide the LLM the request from the application user.

Prompts can be templated so that placeholder variables in the user message are replaced by values from the user when the application runs.

== AI services

